name: macOS

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - 'examples/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - '**'
      - 'examples/**'
      - '.github/workflows/macos.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for actions/upload-release-asset to upload release asset
    runs-on: macos-latest
    
    env:
      RELEASE_NAME: RSGL_engine-dev_macos
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Release Version
      run: |
        echo "RELEASE_NAME=RSGL_engine-${{ github.event.release.tag_name }}_macos" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Setup Environment
      run: | 
        mkdir build
        cd build
        mkdir ${{ env.RELEASE_NAME }}
        cd ${{ env.RELEASE_NAME }}
        mkdir bin
        cd ../..
   
    # Generating static + shared library, note that i386 architecture is deprecated
    # Defining GL_SILENCE_DEPRECATION because OpenGL is deprecated on macOS
    - name: Build Library
      run: |
        clang --version
        
        # Extract version numbers from Makefile
        brew install grep
        
        make
        make release_example

    - name: Generate Artifacts
      run: |
        cp -v ./RSGL_engine ./build/${{ env.RELEASE_NAME }}/bin/
        cp -v -r ./release ./build/${{ env.RELEASE_NAME }}/
        tar -czvf ${{ env.RELEASE_NAME }}.tar.gz ${{ env.RELEASE_NAME }}/bin
        tar -czvf ${{ env.RELEASE_NAME }}-example.tar.gz ${{ env.RELEASE_NAME }}/release
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RELEASE_NAME }}.tar.gz  ${{ env.RELEASE_NAME }}-example.tar.gz
        path: ./build/${{ env.RELEASE_NAME }}.tar.gz ./build/${{ env.RELEASE_NAME }}-example.tar.gz
        
    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/${{ env.RELEASE_NAME }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'  
