name: Windows

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - 'examples/**'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - '**'
      - 'examples/**'
      - '.github/workflows/windows.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for actions/upload-release-asset to upload release asset
    runs-on: windows-latest
    env:
      RELEASE_NAME: RSGL_engine-dev_win${{ matrix.bits }}_${{ matrix.compiler }}
      GNUTARGET: default

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Release Version
      run: |
        echo "RELEASE_NAME=RSGL_engine-${{ github.event.release.tag_name }}_win${{ matrix.bits }}_${{ matrix.compiler }}" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Setup Environment
      run: | 
        dir
        mkdir build
        cd build
        mkdir ${{ env.RELEASE_NAME }}
        cd ${{ env.RELEASE_NAME }}
        mkdir bin
        cd ../../../RSGL_engine
        
    - name: Build (MinGW-w64 64bit)
      run: |
        ${{ matrix.ARCH }}-w64-mingw32-gcc.exe --version
        windres.exe --version
        dir C:\msys64\mingw64\bin
        make CC=${{ matrix.ARCH }}-w64-mingw32-gcc.exe
        make release_example
      shell: cmd
      if: |
        matrix.compiler == 'mingw-w64' &&
        matrix.bits == 64

    - name: Generate Artifacts
      run: |
        copy /Y .\RSGL_engine.exe .\build\${{ env.RELEASE_NAME }}\bin
        xcopy .\release .\build\${{ env.RELEASE_NAME }}\release /E /I /Y
        7z a ./${{ env.RELEASE_NAME }}.zip ./${{ env.RELEASE_NAME }}/bin
        7z a ./${{ env.RELEASE_NAME }}-example.zip ./${{ env.RELEASE_NAME }}/release
        dir
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RELEASE_NAME }}.zip ${{ env.RELEASE_NAME }}-example.zip
        path: ./build/${{ env.RELEASE_NAME }}.zip ./build/${{ env.RELEASE_NAME }}-example.zip
        
    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/${{ env.RELEASE_NAME }}.zip ${{ env.RELEASE_NAME }}-example.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
